#!/bin/bash
if [[ ! $GOPATH ]]; then
    echo "Setting/adding environment variables"

    export GOPATH="$(pwd)"
    export PATH=$PATH:"$(pwd)/bin"

    "export GOPATH=$(pwd)" >> ~/.profile
    "export PATH=$PATH:$(pwd)/bin" >> ~/.profile
fi

if ! [ -d "src/github.com/golang/dep" ]; then
echo "Loading dep"
go get -u github.com/golang/dep/cmd/dep
fi

if ! [ "$(ls -A $GOPATH/src/browser/vendor)" ]; then
    echo "Loading browser"
    cd $GOPATH/src/browser
    dep ensure
fi

if ! [ "$(ls -A $GOPATH/src/storage/vendor)" ]; then
    echo "Loading storage"
    cd $GOPATH/src/storage
    dep ensure
fi

if ! [ "$(ls -A $GOPATH/src/config/vendor)" ]; then
    echo "Loading config"
    cd $GOPATH/src/config
    dep ensure
fi

echo "Done"